title: Code Hackathon, GITAM
description: >-
  We are a team of students in GITAM that aim to promote coding as being fun, challenging and above all, not boring. In collaboration with the Department of CSE, we organise frequent coding competitions called 'Code Hackathons' on a bi-weekly basis on Saturday afternoons. We may on occasion also take classes to discuss and try out various programming techniques and challenges to further enhance your skills.

baseurl: ""
url: "https://codehackathon.github.io/"

permalink: /:title

defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
  style: :compressed

kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
